name: Learn By Test

on:
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Deploy to s3 and commit to pr
      id: deploy-to-s3-and-coment
      uses: ./
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN}}
      env:
        AWS_S3_BUCKET: "fsdafoisjdafoijsado f"
        AWS_ACCESS_KEY_ID: "cool"
        AWS_SECRET_ACCESS_KEY: "dsafsajdofa"
        BUILD_FOLDER: 'public'      # optional: defaults to entire repository
    - name: Print Hello wold
      run: echo "Hello bro"
